// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPogs_jyHPtLJ-PwM0J9VDKf_QffvfqvE',
    appId: '1:530743672199:web:af97427a9f388c17916722',
    messagingSenderId: '530743672199',
    projectId: 'logloglog-6a968',
    authDomain: 'logloglog-6a968.firebaseapp.com',
    databaseURL: 'https://logloglog-6a968-default-rtdb.firebaseio.com',
    storageBucket: 'logloglog-6a968.firebasestorage.app',
    measurementId: 'G-N4QW616DCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuM9VNpzwAS_kjZORIICoy4wV-SRgP89I',
    appId: '1:530743672199:android:a4e10961cc9b276e916722',
    messagingSenderId: '530743672199',
    projectId: 'logloglog-6a968',
    databaseURL: 'https://logloglog-6a968-default-rtdb.firebaseio.com',
    storageBucket: 'logloglog-6a968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_0shZIin6TR4eVQ0xBCTkaEIyiKt1rn0',
    appId: '1:530743672199:ios:434f187496f5635f916722',
    messagingSenderId: '530743672199',
    projectId: 'logloglog-6a968',
    databaseURL: 'https://logloglog-6a968-default-rtdb.firebaseio.com',
    storageBucket: 'logloglog-6a968.firebasestorage.app',
    iosBundleId: 'com.example.flutTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_0shZIin6TR4eVQ0xBCTkaEIyiKt1rn0',
    appId: '1:530743672199:ios:434f187496f5635f916722',
    messagingSenderId: '530743672199',
    projectId: 'logloglog-6a968',
    databaseURL: 'https://logloglog-6a968-default-rtdb.firebaseio.com',
    storageBucket: 'logloglog-6a968.firebasestorage.app',
    iosBundleId: 'com.example.flutTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPogs_jyHPtLJ-PwM0J9VDKf_QffvfqvE',
    appId: '1:530743672199:web:95bd0bda222036ef916722',
    messagingSenderId: '530743672199',
    projectId: 'logloglog-6a968',
    authDomain: 'logloglog-6a968.firebaseapp.com',
    databaseURL: 'https://logloglog-6a968-default-rtdb.firebaseio.com',
    storageBucket: 'logloglog-6a968.firebasestorage.app',
    measurementId: 'G-J2D0LS931L',
  );
}
